#!/bin/sh


# TODO:
# * comment all functions
# * write unit tests
# * add debug/verbose statements
# * write/read config
# * add/rm plugins once with --save
# * habitat_manage

##
# habitat_error(message*)
# print messages to STDERR
#
# message - any number of messages to print to STDERR
##
function habitat_error() {
    while [ $# -gt 0 ]; do
        local message="$1"; shift
        echo "Error: $message" 1>&2
    done
}

##
# habitat_debug(message*)
# print to STDOUT when print level is >= 2
#
# message - any number of messages to print
##
function habitat_debug() {
    if [ "$habitat_print_level" = "debug" ]; then
        while [ $# -gt 0 ]; do
            local message="$1"; shift
            echo "$message"
        done
    fi
}

##
# habitat_verbose(message*)
# print to STDOUT when print level is >= 1
#
# message - any number of messages to print
##
function habitat_debug() {
    if [ "$habitat_print_level" = "verbose" ] || [ "$habitat_print_level" = "debug" ]; then
        while [ $# -gt 0 ]; do
            local message="$1"; shift
            echo "$message"
        done
    fi
}

##
# habitat_cleanup()
# remove all function/variables from the environment that start with habitat_
##
function habitat_cleanup() {
    local func
    (while read -r func; do
        habitat_debug "Unsetting function $func"
        if [ "$func" != "habitat_cleanup" ] &&  [ "$func" != "habitat_debug" ]; then
            unset -f "$func"
        fi
    done <<< "$(declare -F | sed -e 's~declare -f ~~g' | grep -E "^habitat_")")

    local var
    (while read -r var; do
        habitat_debug "Unsetting variable $var"
        unset "$var"
    done <<< "$((set -o posix ; set) | sed -e 's~=.*~~' | grep -E "^habitat_")")

    unset -f "habitat_cleanup"
    unset -f "habitat_debug"
}


# TODO: only source functions and nothing else
##
# habitat_setup()
# source run, setup, and usage functions from plugins
##
function habitat_setup() {
    local author
    local plugin
    for author in "$habitat_plugins/"*; do
        for plugin in "$author/"*; do
            habitat_debug "Going to source $plugin"
            #. "$plugin/habit"
        done
    done
}


##
# habitat_run()
# run plugin setup and run functions
##
function habitat_run() {
    local author
    local plugin
    for author in "$habitat_plugins/"*; do
        for plugin in "$author/"*; do
            habitat_debug "Going to run habitat_${author}_${plugin}_setup()"
            if type -t "habitat_${author}_${plugin}_setup"; then
                :
                #habitat_${author}_${plugin}_setup
            fi
        done
    done

    for author in "$habitat_plugins/"*; do
        for plugin in "$author/"*; do
            habitat_debug "Going to run habitat_${author}_${plugin}_run()"
            if type -t "habitat_${author}_${plugin}_run"; then
                :
                #habitat_${author}_${plugin}_run
            fi
        done
    done
}

##
# habitat_stub(plugin)
# stub out a new plugin
#
# plugin - 'author/repo' of the github url
##
function habitat_stub() {

    if [ -z "$1" ]; then
        habitat_error "Please pass in author/repo"
        return
    fi
    local plugin="$1"
    local name="$(echo "$plugin" | sed 's~/~_~')"
    local dir="$habitat_plugins/$plugin"

    if [ -d "$dir" ]; then
        habitat_error "$plugin already exists!!"
    fi

    mkdir -p "$dir"

    echo "#!/bin/sh
function habitat_${name}_setup() {
    :
}

function habitat_${name}_run() {
    :
}

function habitat_${name}_usage() {
    :
}
" > "$dir/habit"

}



##
# habitat_usage(plugin)
# show usage information
#
# plugin - 'author/repo' of plugin tp show usage for
##
function habitat_usage() {
    if [ -z "$1" ]; then
        echo
        echo "  . habitat <args>"
        echo
        echo "  add       add (a) plugin(s). use --save write a config change"
        echo "  rm        remove (a) plugin(s). use --save to write a config change"
        echo "  stub      stub a plugin in ${habitat_plugins}. ex: stub author/plugin_name"
        echo "  help      show this help menu or plugin help. ex: help author/plugin_name"
    #    echo "  ls        show installed plugins"
    #    echo "  verbose   print everything that habitat does"
    #    echo "  debug     verbose with debug statements"
        echo
    else
        local plugin="$1"; shift
        local name="$(echo "$plugin" | sed 's~/~_~')"
        if type -t "habitat_${name}_usage"; then
            habitat_${name}_usage
        else
            habitat_error "$plugin is not installed or has no usage"
        fi
    fi
}


# TODO check git return codes
##
# habitat_add(plugin*)
# add plugins, pass --save as plugin variable to save additions to config
#
# plugin - any number of 'author/repo' to add
##
function habitat_add() {
    local plugin="$1"; shift

    local dir="$habitat_plugins/$plugin"
    if [ -d "$dir"  ]; then
        habitat_error "Plugin $plugin appears to already be installed"
        return 1
    fi

    git clone "https://github.com/$plugin" "$dir"
    if [ ! -f "$habitat_plugins/$plugin/habit" ]; then
        habitat_error "Plugin $plugin does not contain a habit file removing"
        if [ -d "$dir" ]; then
            rm -rf "$dir"
        fi
        return 1
    else
        echo "Plugin $plugin installed successfully"
    fi

    if [ -n "$save" ]; then
        local plugins="$(habitat_get_config "habitat_plugins")"
        if [ -n "$plugins" ]; then
            plugins="$plugins "
        fi
        habitat_write_config "habitat_plugins" "${plugins}${plugin}"
    fi
}

##
# habitat_rm(plugin*)
# remove plugins, pass --save as plugin variable to save removals to config
#
# plugin - any number of 'author/repo' to remove
##
function habitat_rm() {
    local plugin="$1"; shift;

    local dir="$habitat_plugins/$plugin"
    if [ -d "$dir" ]; then
        echo "Removing plugin $plugin"
        rm -rf "$dir"
    else
        habitat_error "Plugin $plugin does not exist"
        return 1
    fi
}

##
# habitat_read_config(key)
# read a value from the config given its key
#
# key - key to grab the value of
##
function habitat_read_config() {
    local key="$1"; shift
    echo ""
}

##
# habitat_write_config(key, val)
# write a key value pair to the config file
#
# key - key to set
# val - value to set the key to
##
function habitat_write_config() {
    local key="$1"; shift
    local val="$1"; shift
    echo ""
}


##
# habitat_manage()
# add plugins based on config file, and source them
##
function habitat_manage() {
    :
}


##
# habitat_update()
# update all installed plugins with .git directories
##
function habitat_update() {
    local author
    local plugin
    for author in "$habitat_plugins/"*; do
        for plugin in "$author/"*; do
            if [ -d "$plugin/.git" ]; then
                habitat_debug "Going to update $plugin"
                # git pull "$plugin"
                # . $plugin/habit
            fi
        done
    done
}


##
# habitat_update()
# check if the user wants certain first_time functionality
##
function habitat_first_time_setup() {
    # create config and default values
    :
}


#
#
#
# MAIN
#
#
#

if [ -z "$HOME" ]; then
    habitat_error "HOME must be defined in your environment to use habitat"
    return 1
fi

# From Configuration
habitat_debug="1"
habitat_base="$HOME/.habitat"
habitat_plugins="$habitat_base/plugins"
habitat_cli="$habitat_base/habitat"
habitat_dotfiles="$habitat_base/dotfiles"

# Specific Files
habitat_config="$habitat_base/habitatrc"

# The date
habitat_start_seconds="$(date +%s)"


alias habitat=". $habitat_cli"
if [ ! -f "$habitat_config" ]; then
    habitat_first_time_setup
fi
habitat_setup

# user passed in args
if [ -n "$1" ]; then
    action="$1"; shift
    if [ "$action" = "help" ]; then
        habitat_usage "$@"
    elif [ "$action" = "add" ]; then
        habitat_add "$@"
    elif [ "$action" = "rm" ]; then
        habitat_rm "$@"
    elif [ "$action" = "stub" ]; then
        habitat_stub "$@"
    elif [ "$action" = "update" ]; then
        habitat_update"$@"
    else
        habitat_error "Unknown action ${action}. Use help for usage"
    fi
else
    habitat_update
    habitat_manage
    habitat_run
fi

# Cleanup our internal functions
habitat_cleanup
