#!/bin/sh

# TODO:

# To Brainstorm
# * Can we pull down a single file for plugins rather than a folder
#

# MUST DO:
# * write unit tests
# * habitat_manage
# * habitat_update
# * habitat_first_time_setup

# CAN DO:
# * plugin specific config settings
# * warn about updates
# * ask user if they want to update and show code
# * support quotes variables in config?

function habitat_unset_function() {
    unset -f "$1"
}

function habitat_unset_variable() {
    unset "$1"
}
function habitat_source() {
    . "$1"
}


##
# habitat_error(message*)
# print messages to STDERR
#
# message - any number of messages to print to STDERR
##
function habitat_error() {
    while [ $# -gt 0 ]; do
        local message="$1"; shift
        if [ -n "${message:-}" ]; then
            echo "Error: $message" 1>&2
        fi
    done
}

##
# habitat_debug(message*)
# print file descriptor 3 when debug is set. We print to
# and create a thrird file descriptor so that we wont interfere
# with stdout capture of other functions while we are here.
#
# message - any number of messages to print
##
function habitat_debug() {
    if [ -n "${habitat_debug_output:-}" ]; then
        exec 3>&1
        while [ $# -gt 0 ]; do
            local message="$1"; shift
            if [ -n "${message:-}" ]; then
                echo "Debug: $message" 1>&3
            fi
        done
        exec 3>&-
    fi
}

##
# habitat_cleanup()
# remove all function/variables from the environment that start with habitat_
##
function habitat_cleanup() {
    local func
    while read -r func; do
        if [ "$func" = "habitat_cleanup" ]; then
            continue
        elif  [ "$func" = "habitat_debug" ]; then
            continue
        elif [ "$func" = "habitat_unset_function" ]; then
            continue
        elif [ "$func" = "habitat_unset_variable" ]; then
            continue
        fi
        habitat_debug "Unsetting function $func"
        habitat_unset_function "$func"
    done <<< "$(declare -F | grep "^declare -f habitat_" | sed 's~declare -f ~~g' )"

    local var
    while read -r var; do
        if [ "$var" = "habitat_debug_output" ]; then
            continue
        fi
        habitat_debug "Unsetting variable $var"
        habitat_unset_variable "$var"
    done <<< "$((set -o posix ; set) | sed -e 's~=.*~~' | grep -E "^habitat_")"


    habitat_debug "Unsetting function habitat_debug"
    habitat_debug "Unsetting variable habitat_debug_output"
    habitat_debug "Unsetting function habitat_cleanup"
    habitat_debug "Unsetting function habitat_unset_function"
    habitat_debug "Unsetting function habitat_unset_variable"

    habitat_unset_function "habitat_debug"
    habitat_unset_variable "habitat_debug_output"
    habitat_unset_function "habitat_cleanup"
    habitat_unset_function "habitat_unset_variable"
    habitat_unset_function "habitat_unset_function"
    return 0
}


##
# habitat_source_installed_plugins()
# source run, setup, and usage functions from plugins
##
function habitat_source_installed_plugins() {
    local base_dir="$1"
    local author
    local plugin
    local author_dir
    local plugin_file
    for author_dir in "$base_dir/"*; do
        # as this would normally be a long dir rather than just the author name
        author="$(basename "$author_dir")"
        if [ "$author" = "*"  ]; then
            habitat_debug "Found no authors in installed plugins"
            return 1
        fi
        for plugin_file in "$author_dir/"*; do
            plugin="$(basename "$plugin_file")"
            if [ "$plugin" = "*"  ]; then
                habitat_error "Found no plugins for author $author"
                break
            fi
            habitat_debug "Sourcing plugin $author/$plugin in environment"
            habitat_source "$plugin_file"
        done
    done
    return 0
}


##
# habitat_run()
# run plugin setup and run functions
##
function habitat_run() {
    local plugin
    local plugin_underscore
    for plugin in $habitat_plugin_list; do
        plugin_underscore="$(echo "$plugin" | sed 's~/~_~')"
        habitat_debug "Going to run habitat_${plugin_underscore}_setup()"
        if type -t "habitat_${plugin_underscore}_setup"; then
            habitat_${plugin_underscore}_setup
        else
            habitat_error "$plugin does not have a setup function!!"
        fi
    done
    for plugin in $habitat_plugin_list; do
        plugin_underscore="$(echo "$plugin" | sed 's~/~_~')"
        habitat_debug "Going to run habitat_${plugin_underscore}_setup()"
        if type -t "habitat_${plugin_underscore}_run"; then
            habitat_${plugin_underscore}_run
        else
            habitat_error "$plugin does not have a run function"
        fi
    done
}

##
# habitat_stub(plugin)
# stub out a new plugin
#
# plugin - 'author/repo' of the github url
##
function habitat_stub() {

    if [ -z "$1" ]; then
        habitat_error "Please pass in author/repo"
        return
    fi
    local plugin="$1"
    local name="$(echo "$plugin" | sed 's~/~_~')"
    local plugin_file="$habitat_plugins_dir/$plugin"

    if [ -f "$plugin_file" ]; then
        habitat_error "$plugin already exists!!"
    fi

    mkdir -p "$(dirname "$plugin_file")"

    local stub_contents="#!/bin/sh
function habitat_${name}_setup() {
    :
}

function habitat_${name}_run() {
    :
}

function habitat_${name}_options() {
    :
}

"

    habitat_debug "Creating stub for $plugin in $plugin_file"
    habitat_debug "With Contents" "$stub_contents"
    echo "$stub_contents" > "$plugin_file"

}





##
# habitat_usage(plugin)
# show usage information
#
# plugin - 'author/repo' of plugin tp show usage for
##
function habitat_usage() {
        echo
        echo "  . habitat <options>"
        echo
        echo "  add       add (a) plugin(s). use --save write a config change"
        echo "  rm        remove (a) plugin(s). use --save to write a config change"
        echo "  stub      stub a plugin in ${habitat_plugins_dir}. ex: stub author/plugin_name"
        echo "  help      show this help menu or plugin help. ex: help author/plugin_name"
        echo "  --debug   show debug statements to stdout"
    #    echo "  ls        show installed plugins"
    #    echo "  update    go through a plugin update progress"
    #    echo "  install   install plugins based upon config file"
        echo
}


##
# habitat_add(plugin*)
# add plugins, pass --save as plugin variable to save additions to config
#
# plugin - any number of 'author/repo' to add
##
function habitat_add() {
    while [ $# -gt 0 ] ; do
        local plugin="$1"; shift
        if [ -z "$plugin" ]; then
            continue
        fi
        local dir="$habitat_plugins_dir/$plugin"
        if [ -d "$dir"  ]; then
            habitat_error "Plugin $plugin appears to already be installed"
            continue
        fi

        # need to decalre local variables before capture
        # or else we won't correctly grab the result code
        local output=""
        output="$(git clone "https://github.com/$plugin" "$dir")"
        if [ "$?" -ne "0" ]; then
            habitat_error "Git Failed" "$output"
            continue
        fi
        if [ ! -f "$habitat_plugins_dir/$plugin/habit" ]; then
            habitat_error "Plugin $plugin does not contain a habit file removing"
            if [ -d "$dir" ]; then
                rm -rf "$dir"
            fi
            continue;
        fi
        echo "Plugin $plugin installed successfully"
        if [ -n "$habitat_save_to_config" ]; then
            local plugins="$(habitat_get_config "habitat_plugins_dir")"
            if [ -n "$plugins" ]; then
                plugins="$plugins "
            fi
            habitat_write_config "habitat_plugins_dir" "${plugins}${plugin}"
        fi
    done
}

##
# habitat_rm(plugin*)
# remove plugins, pass --save as plugin variable to save removals to config
#
# plugin - any number of 'author/repo' to remove
##
function habitat_rm() {
    while [ $# -gt 0 ] ; do
        local plugin="$1"; shift;
        if [ -z "$plugin" ]; then
            continue
        fi
        local dir="$habitat_plugins_dir/$plugin"
        if [ ! -d "$dir" ]; then
            habitat_error "Plugin $plugin does not exist"
            continue
        fi
        rm -rf "$dir"
        echo "Successfully Removed plugin $plugin"
        if [ -n "$habitat_save_to_config" ]; then
            local plugins="$(habitat_get_config "habitat_plugins_dir" | sed "s~$plugin~~")"
            habitat_write_config "habitat_plugins_dir" "${plugins}${plugin}"
        fi
    done
}

##
# habitat_read_config(key)
# read a value from the config given its key
#
# key - key to grab the value of
##
function habitat_read_config() {
    local key="$1"; shift
    result="$(cat "$habitat_config_file" | grep "$key" | sed "s~$key=~~")"
    if [ -z "$result" ]; then
        result="$(echo "")"
    fi
    echo "$result"
    habitat_debug "Found that $key was $result in config file"
}

##
# habitat_write_config(key, val)
# write a key value pair to the config file
#
# key - key to set
# val - value to set the key to
##
function habitat_write_config() {
    local key="$1"; shift
    local val="$1"; shift
    if [ -z "$key" ]; then
        return 1
    fi
    if [ -n "$( echo "$habitat_config_file" | grep "$key=")" ]; then
        habitat_debug "Found that $key already exists going to set to $val"
        cat "$habitat_config_file" | sed "s~$key=.*~$key=$val" > "$habitat_config_file"
    else
        habitat_debug "Found that $key does not exist appending to config as $val"
        echo "$key=$val" > $habitat_config_file
    fi
}




##
# habitat_update()
# update all installed plugins with .git directories
##
function habitat_update() {
    local author
    local plugin
    for author in "$habitat_plugins_dir/"*; do
        for plugin in "$author/"*; do
            if [ -d "$plugin/.git" ]; then
                habitat_debug "Going to update $plugin"
                "$(cd $plugin && git pull "$plugin")"
                . $plugin/habit
            else
                habitat_debug "Cannot update $plugin as it is not in git"
            fi
        done
    done
}


##
# habitat_update()
# check if the user wants certain first_time functionality
##
function habitat_first_time_setup() {
    # create config and default values
    :
}

##
# habitat_check_update()
# check wether their are updates for the habitat cli or plugins
##
function habitat_check_update() {
    :
}

##
# habitat_manage()
# add plugins based on config file, and source them
##
function habitat_manage() {
    :
}




##
# habitat_main(parent_lineno, message, code)
# parent_lineno - line number reported by the trap
# message       - error message
# code          - code to exit with
##
function habitat_trap_error() {
    local parent_lineno="${1:-}"; shift
    local message="${1:-}"; shift
    local code="${1:-1}"; shift

    if [ -z "$message" ]; then
        message=""
    fi
    habitat_error "Error on or near line ${parent_lineno}: ${message}; exiting with status ${code}"
    habitat_cleanup
    return "${code}"
}



##
# habitat_main($@)
# $@ - all args that have been passed to the script
##
function habitat_main() {
    # grab out --save and --debug
    habitat_argument_count="${#:0}"
    while [ $habitat_argument_count -gt 0 ]; do
        habitat_argument="$1"; shift
        if [ "$habitat_argument" = "--save" ]; then
            habitat_save_to_config="1"
        elif [ "$habitat_argument" = "--debug" ]; then
            habitat_debug_output="1"
        else
            set -- "$@" "$habitat_argument"
        fi
        habitat_argument_count=$((habitat_argument_count-1))
    done

    # throw errors if --save is passed in a bad way
    if [ -n "${habitat_save_to_config:-}" ] && [ -z "${1:-}" ]; then
        habitat_error "--save will do nothing without being used with add or rm"
        return 1
    elif [ -n "${habitat_save_to_config:-}" ] && [ -n "${1:-}" ]; then
        if [ "$1" != 'add' ] || [ "$1" != "rm" ]; then
            habitat_error "--save will do nothing with action $1"
        fi
    fi


    if [ -n "${1:-}" ]; then
        habitat_option="$1"; shift
        if [ "$habitat_option" = "help" ]; then
            habitat_usage "$@"
        elif [ "$habitat_option" = "add" ]; then
            habitat_add "$@"
        elif [ "$habitat_option" = "rm" ]; then
            habitat_rm "$@"
        elif [ "$habitat_option" = "stub" ]; then
            habitat_stub "$@"
        elif [ "$habitat_option" = "update" ]; then
            habitat_update"$@"
        elif type -t habitat_"$(echo "$habitat_option" | sed 's~/~_~')"_options; then
            habitat_"$(echo "$habitat_option" | sed 's~/~_~')"_options "$@"
        else
            habitat_error "Unknown option ${habitat_option}. Use help for usage"
            return 1
        fi
    else
        habitat_update
        habitat_manage
        habitat_run
    fi
}



# TODO: more dynamic way to get habitat_base
# Requirements
if [ -z "$HOME" ]; then
    habitat_error "habitat_base must be defined in your environment to use habitat"
    return 1
fi

if ! command -v git > /dev/null; then
    habitat_error "git must be installed to use habitat!"
    return 1
fi


# defines
habitat_base_dir="$HOME/Projects/.habitat"
habitat_installed_plugins_dir="$habitat_base_dir/plugins/installed"
habitat_git_plugins_dir="$habitat_base_dir/plugins/git"
habitat_cli_file="$habitat_base_dir/habitat"
habitat_dotfiles_dir="$habitat_base_dir/dotfiles"
habitat_config_file="$habitat_base_dir/habitatrc"
habitat_run_unit_test=""

# Ever Changing Data
habitat_start_seconds="$(date +%s)"
habitat_save_to_config=""
habitat_version="1.0.0"
alias habitat=". $habitat_cli_file"

if [ -n "${1:-}" ] && [ "$1" = "--unit_testing" ]; then
    habitat_run_unit_test="1"
fi

# if unit testing dont automatically run anything
if [ -z "$habitat_run_unit_test" ]; then

    trap -- 'habitat_trap_error ${LINENO}' ERR SIGTERM SIGINT SIGHUP SIGQUIT
    if [ ! -f "$habitat_config_file" ]; then
        habitat_first_time_setup
    fi

    habitat_debug_output=""
    habitat_source_installed_plugins "$habitat_installed_plugins_dir"


    habitat_main "$@"

    # Cleanup our internal functions
    habitat_cleanup
    trap --
fi
