#! /bin/sh


#*==============================================================================
# habitat_prep
#
# Prepare the habitat environment, by adding the bin directory to the path, and
# adding a few keywords for habitat directories
#
#*==============================================================================
# Base Folders
export habitat_base="$HOME/.habitat"
export habitat_cli="$habitat_base/turtle"
export habitat_storage="$habitat_base/storage"
export habitat_bin="$habitat_base/bin"
export habitat_extensions="$habitat_base/extensions"
export habitat_settings="$habitat_base/settings"
export habitat_lib="$habitat_base/lib"

# Specific Folders
export habitat_tmp="$habitat_storage/tmp"
export habitat_backup="$habitat_storage/backup"
export habitat_logs="$habitat_storage/logs"

# Specific Files
export habitat_log_file="$habitat_logs/turtle.log"
export habitat_config_file="$habitat_settings/turtle.cfg"

# For things to log to
export CUSTOM_LOG_FILE="$habitat_log_file"
export CUSTOM_BACKUP="$habitat_backup"
export CUSTOM_CONFIG="$habitat_config_file"

# The date
export habitat_start_seconds="$(date +%s)"

# Set log level
: > "$habitat_log_file"
# Assure that we have a good environment
"$habitat_bin"/log.sh --header "Prep"

"$habitat_bin"/log.sh --result unalias -a

alias habitat="source $habitat_cli"
alias turtle="source $habitat_cli"
"$habitat_bin"/log.sh "Added turtle and habitat alias"

rm -rf "$habitat_tmp"/*
"$habitat_bin"/log.sh "Cleaned $habitat_tmp"

export PATH="$("$habitat_bin"/string.sh --split ":" "$PATH" | "$habitat_bin"/string.sh --joinu ":")"

log.sh --result data.sh --link "$habitat_cli" "$HOME/.bash_profile"

source "$habitat_lib/lib.sh"
source "$habitat_lib/cleanup.sh"
source "$habitat_lib/dependancy_management.sh"
source "$habitat_lib/extension.sh"
source "$habitat_lib/settings.sh"
source "$habitat_lib/stub_extension.sh"

action=""
save="1"
function habitat_usage() {
    echo
    echo "  . turtle <options>"
    echo
    echo "  install|add      install a dependancy to your environment"
    echo "  remove|uninstall uninstall a dependancy from your environment"
    echo "  save             save/install a dependancy to your environment list"
    echo "  setting          Can be set to new, example, or a github repo"
    echo "  stub             stub an extension name in the extensions directory"
    echo
    exit 0
}

while [ "$#" -gt "0" ]; do
    arg="$1"; shift
    case $arg in
        --help)
            habitat_usage "$help"
        ;;
        --install|--add|--uninstall|--remove|--settings|--stub)
            action="$arg"
            arg1="$1"; shift
        ;;
        *)
            error "Invalid Argument $arg"
        ;;
    esac
done


if [ "$action" = "main" ]; then
    # Dependancy Maanagement
    habitat_dependancy_management

    # Extension Deployment
    habitat_extension_deployment

elif [ "$action" = "stub" ]; then
    habitat_stub_extension
elif [ "$action" = "install" ]; then
    habitat_install_extension
elif [ "$action" = "uninstall" ]; then
    habitat_remove_extension
elif [ "$action" = "settings" ]; then
    habitat_install_settings
fi
# Cleanup
habitat_cleanup
