#! /bin/sh
source "$( cd "$(dirname $0 )/.." && pwd)/lib/main.sh"

help="stub Question to ask the user$nl"
help+="install|add Pipe deliminated answers where default is the first asd|dsa|no|yes $nl"
while [ "$#" -gt "0" ]; do
    arg="$1"; shift
    case $arg in
        --help)
        usage "$help"
        ;;
        --install|--add)
			action="$arg"
        ;;
        --uninstall|--remove)
			action="$arg"
        ;;

		--uninstall|--remove)
			action="$arg"
        ;;

        *)
            argument_error "Invalid Argument $arg"
        ;;
    esac
done

habitat_extensions="$( cd "$(dirname "$0")" && pwd )/test"
function get_extension_dirs() {
	for author_dir in "$habitat_extensions/"*; do
		for extension in "$author_dir/"*; do
			echo "$extension"
		done
	done
}

while read -r extension_dir; do
	if [ ! -d "$extension_dir/.git" ]; then
		echo "$extension_dir is not under version control"
	else
		LOCAL="$(cd "$extension_dir" && git rev-parse @{0})"
		REMOTE="$(cd "$extension_dir" && git rev-parse @{u})"
		BASE="$(cd "$extension_dir" && git merge-base @{0} @{u})"
		if [ "$LOCAL" = "$BASE" ]; then
			echo "Update possible for $extension_dir"
		fi
		# Check if git update
	fi
done <<< "$(get_extension_dirs)"
